title: The Wild At Heart Wiki
email: the.wild.at.heart.wiki@gmail.com
description: >-
  Wiki of the game The Wild At Heart.
baseurl: ""
url: ""
github_username: iriiiina

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Other
safe: true
timezone: "Europe/Tallinn"
encoding: utf-8

collections_dir: pages
collections:
  inhabitants:
    title: "Inhabitants"
    output: true
    order:
      - wake.html
      - kirby.html
      - grey_coat.html
      - brussel.html
      - scrap_heap.html
      - crows_nest.html
      - litterbox.html
      - paper_planes.html
      - toothpicks.html
      - can_dance.html
      - cant_dance.html
      - cath.html
      - aatto.html
      - rubbish.html
  spritelings:
    title: "Spritelings"
    output: true
    order:
      - twigling.html
      - emberling.html
      - shiverling.html
      - barbling.html
      - lunaling.html
  hostile_beasts:
    title: "Hostile Beasts"
    output: true
    order:
      - gloomcap.html
      - bloopcap.html
      - knightcap.html
      - buff_puff.html
      - gumblop.html
      - blazeblop.html
      - bitterblop.html
      - lotblop.html
      - lilblop.html
      - bushback.html
      - spoilback.html
      - frostback.html
      - buffback.html
      - lootback.html
      - bloat_toad.html
      - crud_croaker.html
      - torch_throat.html
      - woodsy_faefly.html
      - frosty_faefly.html
      - faefly_hive.html
      - groggthud.html
      - the_never.html
  lost_journal_pages:
    title: "Lost Journal Pages"
    output: true
  key_items:
    title: "Key Items"
    output: true
  map:
    title: "Map"
    output: true
  flora:
    title: "Flora"
    output: true
  missions:
    title: "Missions"
    output: true
